- README.md
- entrypoint.sh
* Skips if commit is already tagged (https://github.com/anothrNick/github-tag-action/issues/11)
* Adds customisable `DEFAULT_BUMP` config, defaults to `minor`.
> Skip version bump if commit already has tag (#11)

- Dockerfile
- README.md
- action.yml
- entrypoint.sh
Implements #16 
Creates the newly required metadata file at the root of the action directory, per https://help.github.com/en/articles/metadata-syntax-for-github-actions and https://github.blog/changelog/2019-10-10-the-github-actions-marketplace-now-requires-an-actions-metadata-file/
This defines a new output parameter (https://help.github.com/en/articles/metadata-syntax-for-github-actions#outputs) as `new_tag` that subsequent actions can use later in the workflow.
> Create action.yml metadata. Set new tag to output for other builds.

- README.md
- entrypoint.sh
Fixes #18
The goal of this PR is to avoid confusion when a Pull Request or a feature branch computes a version number. This lets the user define that only the master branch should be tagged.
Other branches or pull requests will compute a new version number (bumped as usual). But the version will be marked as a pre-release thanks to the prerelease postfix.
So, instead of computing 1.2.3, the script will compute 1.2.3-1a2b3c4.
And the next revision of the Pull Request (or feature branch build) will compute a similar version 1.2.3-2b3c4d5 (since no tag was put and supposedly master did not evolve in the meantime).
Example of configuration:
```
env:
RELEASE_BRANCHES: "master,release/*"
```
or
```
env:
RELEASE_BRANCHES: "production"
```
or (which is the default behavior)
```
env: …
```
> Pre-release mode

- README.md
- entrypoint.sh
This will allow the tag to be set directly from the action script.
Useful when tagging docker images based on the version of the base images they are based on.
> Added new 'Custom_tag' parameter

- README.md
Summary:
The convention from other actions is to take inputs with the `with:` object
which is not the case for this action. This change adds an explicit example
to the README to hint developers where the key/value is expected.
> Add an Explicit Example of Optional Env Var

- entrypoint.sh
Two quick fixes:
* Use the `git for-each-ref` command to extract the last semver tag *in order*, and only if it actually looks like a semver.
* If semver fails at generating a new tag, don't just add `v` or `$pre_release` to an empty string.
> Extract only valid semver tags, only add v if we have a new tag

- README.md
- entrypoint.sh
This PR add the dry_run feature to allow more complex version bumping processes. While this is not necessarily needed for NPM, it makes a lot of sense with other packaging tools or when more complex sets should be done for finalising a tag-release.
I tested this with [phish108/node-foobar](/phish108/node-foobar) without problems. 
The actions are setup as follows: 
```yml
jobs:
release: 
needs: build
runs-on: [ubuntu-latest]
strategy:
matrix:
node-version: 
- 12
steps:
- uses: actions/checkout@v2
- name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v1
with:
node-version: ${{ matrix.node-version }}
- run: |
git config --local user.email "action@github.com"
git config --local user.name "GitHub Action"
- uses: phish108/github-tag-action@p1.17.4
id: tagger
env: …
```
> Adding DRY_RUN feature that fixes #47

- entrypoint.sh
Fixes https://github.com/anothrNick/github-tag-action/issues/53.
This PR changes the log format from `oneline` to [`%B`](https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-B), which prints the raw body (unwrapped subject and body).
> Allow bump message in body of commit message

- entrypoint.sh
As pointed out in #49 GITHUB_REF can be misleading. Because it is impossible to overwrite this environment variable, I suggest to be failsafe and use the actual checkout branch instead the branch that triggered the workflow.
> use the checkedout branch for release checking

- .github/workflows/main.yml
- README.md
- action.yml
- entrypoint.sh
The initial version might be useful for new projects without tags.
Outputting part might be useful for later steps to bump for instance `setup.py`
> Add initial version parameter and output part which was bumped

- README.md
- entrypoint.sh
This addresses https://github.com/anothrNick/github-tag-action/issues/56
By setting `DEFAULT_BUMP=none`, automatic bumping will be disabled. You must provide `#major`/`#minor`/`#patch` to your git commits to trigger the version bump.
> Adding support for DEFAULT_BUMP=none

- README.md
- entrypoint.sh
resolves anothrNick/github-tag-action#51
To enable the desired behavior of the ticket, whilst not altering existing behavior I added a `TAG_CONTEXT` env var that swaps out the functionality of the `git for-each-ref` and subs in the `git describe`. The filtering behavior of the original is carried to the `describe` functionality. 
```yaml
env:
- TAG_CONTEXT=branch
```
Will exit with a non-zero code if a unrecognised `TAG_CONTEXT` is provided.
> [#51] Added ability to bump tags from the checked out branch

- entrypoint.sh
Found that there were several failure modes which happened silently (action reported success).
1. `$tag` was used before its conditional initialization. I moved the initialization block to before first use.
2. Added `set -o pipefail` to more quickly fail if parts of the shell script failed...
3. Added a very rudimentary block to verify that the `curl` post to github succeeded, and created an appropriate tag.
This should generally be compatible with existing uses, though it's possible that some environments have subtle misconfigurations which cause partial failures to silently lurk, those users may go from partial functionality to a binary failure case.
> Some reliability fixes

- entrypoint.sh
The former implementation matched on versions like 25.0.0-RC1 or 1.3.4-M2
> use actual regexp match instead of globs for tag matcher

- entrypoint.sh
Create the newly new git tag locally (not only remotely).
This would prevent hacking like: https://github.com/golang-templates/seed/blob/master/.github/workflows/build.yml#L35
I imagine they may be more use cases where it would be helpful.
Basically I have done it this way, because of the issue described here: https://github.com/anothrNick/github-tag-action/issues/64
I do not want to create a dedicated Personal GitHub Token. I want to create a repository template that anyone can use with minimal interaction.
> Create local git tag

- entrypoint.sh
Previously, the action would fail if `DEFAULT_BUMP` was set to `none`. This fixes the issue in a cleaner way than this other pull-request #78
> Fix: Exiting when default bump set to none

- README.md
- entrypoint.sh
For larger projects, printing the git logs can be very noisy in action logs, making it difficult to debug, etc. This optional flag is defaulted to 'true' to keep functionality familiar for existing workflows.
> #minor This adds an optional "verbose" tag

- README.md
- entrypoint.sh
The default release branches are `main` and `master`
> [release branches] add main as default release branch

- entrypoint.sh
Currently the regex that gets the last tag matches not only semver tags.
Dots weren't escaped. As a result, the regex would match not only semver tags, but also the values `12345`, `1a23a345`, and so on.
Log of the action when the most recent tag is `123123123`:
```
*** CONFIGURATION ***
DEFAULT_BUMP: minor
WITH_V: false
RELEASE_BRANCHES: .*
CUSTOM_TAG: 
SOURCE: .
DRY_RUN: false
INITIAL_VERSION: 1.0.0
TAG_CONTEXT: repo
PRERELEASE_SUFFIX: beta
VERBOSE: true
Is .* a match for master
pre_release = false
change!
minor
Bumping tag 123123123. 
New tag                             <--- nothing
0.1.0
0.1.1
0.1.2
0.2.0
1.0.0
1.1.0
123123123
```
> Fix a buggy tag regex

- entrypoint.sh
This PR replaces https://github.com/anothrNick/github-tag-action/pull/133
This PR address the lingering issue in #133 where `with_v = true` would always use the most recent `v` prefix tag even if it wasn't the actual most recent tag.
For example, `with_v` would update from `v2.6.13` to `v2.6.14` even if the tag `2.6.20` exists.
The approach taken here is simple:
- pull all tags that match semver with or without the `v` prefix
- use the semver npm script to normalize and sort the list. [semver will automatically strip leading](https://docs.npmjs.com/cli/v6/using-npm/semver#versions) `v` from version tags
- after the version has been bumped, prefix version with `v` if `with_v` is true
> Semver sort

- Dockerfile
- entrypoint.sh
Tested locally works without problems.
> 3.15 bump + gitaction runner unsafe.directory hotfix

- README.md
- entrypoint.sh
- too much variable reuse
- now u can bump vX.X.X-suff.X properly ie, v0.0.1-dev.0 bumps to v0.0.1-dev.1 for example for branch work rc release etc
- don't trust semver to tail, prefer head
- changed rexeg slightly to ignore `latest` non semver tags
- sorted pre-release mismatch when ur branch name contains master or main to behave correctly as pre-release anyway
- other small bits here and there
feel free to test from my fork: `sbe-arg/github-tag-action@1.39.6`
> fixes for: suffix.X in pre-tags bumps & refarctor some of the shell logic

- Dockerfile
- entrypoint.sh
- fixes tag if there are no existing tags
- closes https://github.com/anothrNick/github-tag-action/issues/166
- also moves the copy command in the docker image to after the install commands, so you can take advantage of docker layer caching when building the image locally
before the change, the tag variable was set to the last line of the semver help message ("multiple versions to the utility will just sort them.")
Comments out lines in `entrypoint.sh` after line 157 (after the `# set outputs` line) and all `echo ::set-output` lines
builds docker image
runs docker image with entrypoint as bash
Runs these lines to test
```bash
export GITHUB_WORKSPACE=/workspace
mkdir -p ${GITHUB_WORKSPACE} && cd ${GITHUB_WORKSPACE} && git init && git config --global user.name "Jane Doe" && git config …
```
> fix: create tag if there are no existing tags

- .github/pull_request_template.md
- .github/workflows/lint.yml
- .github/workflows/main.yml
- Dockerfile
- README.md
- Add minimal PR template
- Update docs to pin checkout action to v3
- Update node docker image from 12 to 16 (Fixes https://github.com/anothrNick/github-tag-action/issues/172)
- Add bash linting (on PR) (Fixes https://github.com/anothrNick/github-tag-action/issues/171)
- Add dockerfile linting (on PR)
- Add Github Actions linting (on PR)
- Update apk install to best practice --no-cache option
> update docs, node, add docker & bash linting

- .github/workflows/test.yml
- Add basic test that checks out the action on the current branch/fork and checks that the tagging (with dry_run) returns an expected value.
- Fixes #174
- No
- No code changes.
- On this PR the tests will have passed.
-
> Add basic test of Action

- .github/workflows/main.yml
It will not run otherwise as the commit message is made for manual or scheduled trigger bumps
> run the major tag on every release

- .github/workflows/main.yml
regex had v requirement
@sammcj sorry and thanks for the quick reviews, not my best day today missing the V vs non-V formats
> Hotfix: remove v check for major tag 

- entrypoint.sh
> fix: safe sub directory

- entrypoint.sh
Reverts anothrNick/github-tag-action#149
This seems to have caused issues for some users that have had to downgrade to the previous release.
- https://github.com/anothrNick/github-tag-action/issues/182
- https://github.com/anothrNick/github-tag-action/issues/181
> Revert "fix: safe sub directory"

- entrypoint.sh
Adding **new_tag** variable when **tag_commit** is equal **commit**,  where solves some issues when there aren't new commits, it needs to take the previous existing tag.
Do any of the following changes break current behaviour or configuration?
- **NO**
On my personal project, I was facing an issue related to the tags and I checked that one of my branches didn't have a new commit, and then I realized that the new tag was missing because it wasn't being set by getting the previous tag.
> Update entrypoint.sh, by adding new_tag value when there are no new commits

- .github/workflows/main.yml
Seems to be a bug does not allow to use self major while bumping major in this repo. Makes sense though https://github.com/anothrNick/github-tag-action/actions/runs/3139501775/jobs/5099976842#step:1:35
Major does not work in referenced projects. So seems to be a github `@1` resolution thinking is a sha and not a tag
@sammcj merge once approved if I'm not around
> Fix bump major release in self-action

- entrypoint.sh
Separate from the == as can lead to unintended -like results unless a wildcard is specified in the list
> Fix wildcard filters for branches

- entrypoint.sh
The logs from the tag run don't show the actual tag to be used if the
`with_v` option is set. This fixes that.
- YES / **NO**
-
-
> Print actual tag to be used when using `with_v`

- README.md
- entrypoint.sh
This PR add an option to choose custom string token to be considered as `#major`, `#minor`, `#patch`, `#none`. With the change and new configuration introduced, one could define their own repo convention.  As an example, one could set the `MINOR_STRING_TOKEN` config to `[minor]`, `[MINOR]`, `(minor)`, or `<minor>` to trigger minor version bump. It doesn't even have to contain the keyword "minor".
- YES / **NO**
```shell
#!/bin/bash
major_string_token=${MAJOR_STRING_TOKEN:-#major}
minor_string_token=${MINOR_STRING_TOKEN:-#minor}
patch_string_token=${PATCH_STRING_TOKEN:-#patch}
none_string_token=${NONE_STRING_TOKEN:-#none}
log="commit message string #minor [major]"
case "$log" in
*$major_string_token* ) …
```
> Custom major, minor, patch, none commit message string token

- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- README.md
- entrypoint.sh
Solves https://github.com/anothrNick/github-tag-action/issues/194
I personally think this should be the expected behaviour when we merge we define the future of this branch bump in the merge commit message not necessarily by a random commit lost down in the commit history making it hard to track.
> Change log ack from all logs to merge commit log

- .github/workflows/main.yml
With the current history log using bump tags we cannot get a new 1 and v1 tag bump unless we use the last commit which is using version 1.52.0 or later.
I think is safe to use master there. As we test in latest:master.
1 and v1 are failing due wrong interpretation of commit history bumps https://github.com/anothrNick/github-tag-action/actions/runs/3180053697/jobs/5183196350 
@sammcj  merge once approved.
> Use master for auto releasing this repo

- .github/workflows/main.yml
- .github/workflows/test.yml
- entrypoint.sh
Okay the problem here was output tag as replaced with $new tag and that is breaking change so added new output old_tag instead and left the tag output as was before untill v2 
https://github.com/anothrNick/github-tag-action/issues/200
> Hotfix: sort output tag mismatch reverting breaking change

- entrypoint.sh
Resolves #205 
Updates how output is being set to remove warnings and prevent breakage once Github removes support for the `set-output` echo statements.
- **NO**
- Tested locally by setting the environment variable to `/dev/stdout` to see the correct output.
- `test.yml` workflow should validate the functionality by executing this changed action.
- Should not be any unknowns, as this is following Github's documentation on how to set outputs as of 2022-10-11
> Update set-output to use GITHUB_OUTPUT file

- entrypoint.sh
Revert formatting change in ac1e937 which causes only the commit subject to be parsed. Fixes #213 
- NO
- Manual testing: I tested major, minor and default changes using both the commit head and body. No issues were observed.
- @sbe-arg was there a reason you chose %s over %B in ac1e937? Are there any side-effects of %B that we need to avoid?
> Parse commit body

- .github/workflows/main.yml
github.ref_name at checkout is limited within the same repo by default
Works when branches merged are from the same repo but breaks on forks due token permissions
> Fix tag bumps

- .dockerignore
- .github/workflows/build-docker-image.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- Dockerfile
- action.yml
- prebuild.Dockerfile
Fix for https://github.com/anothrNick/github-tag-action/issues/163
- Build, label, tag and publish Docker image to Githubs image repository.
- Simplify Action's Dockerfile to pull the built image.
- No
- I've forked the repo and done the build and publish.
- Tested I'm able to pull the built image locally.
- I haven't tested the changes in _this_ repo.
- I don't know what package permissions @anothrNick has setup on this repo, if it's default I believe public repos have public packages.
Once merged, the Action should be tested to ensure it's operating the same.
> feat: pre-build dockerfile

- README.md
- entrypoint.sh
Variable BRANCH_HISTORY" `full|last` allows to select the length of the history for finding bump keywords.
As per examples:
```
history='full'
declare -A history_type=( 
["last"]="$(git show -s --format=%B)" \
["full"]="$(git log master..HEAD --format=%B)" \
)
log=${history_type[${history}]}
printf "History:\n---\n%s\n---\n" "$log"
History:
---
history type
POC log
---
```
```
history='last'
declare -A history_type=( 
["last"]="$(git show -s --format=%B)" \
["full"]="$(git log master..HEAD --format=%B)" \
)
log=${history_type[${history}]}
printf "History:\n---\n%s\n---\n" "$log"
History:
---
history type
---
```
fixes https://github.com/anothrNick/github-tag-action/issues/211
> Select last commit or full branch history for analysis of #bumps

- README.md
- entrypoint.sh
> Fix: Get the default branch from env vars also allow to overwrite as parameter

- entrypoint.sh
We do this check in normal runs but we are not contemplating action re runs of pre-releases, this solves it.
Not the best approach but is not doing any refactor of existing code
> Skip if there are no new commits in pre-release re runs

- entrypoint.sh
This not really a hotfix more like a user warning to set the default_branch if using a workflow approach that does not contemplate PRs.
Open question, do we want to try to identify if master or main exist and define that as default branch as workaround?
> Exit with error if default branch is not set in non prs

- README.md
- entrypoint.sh
The current implementation of full git log breaks in squash and rebase due missing HEAD using suggestion from @jonavos here https://github.com/anothrNick/github-tag-action/issues/232#issuecomment-1372299198
Unsure how this will behave in pre-release re runs as the pre_tag_commit is not considered in this log capture. But thats another missing feature we can review this at another stage
> Hotfix - Add log compare as default instead of full log

- README.md
- entrypoint.sh
As suggested by @vancejc-mt  in https://github.com/anothrNick/github-tag-action/issues/243 we should only validate the default_branch when history is set to full
some testing here fixing the HEAD symbolic issue https://github.com/anothrNick/github-tag-action/actions/runs/3854410905/jobs/6568375010#step:3:130 
Added warning to users in readme when combining history full and the default branch is something other than main or master.
> Hotfix - Validate default_branch only when history type full

- README.md
used more recent version for my trials, figured that 1.55.0, which is mentioned in the README will not respect commit keywords and always default to the DEFAULT_BUMP. version 1.61.0 does not, therefore better example IMO.
> fix README used version

- Dockerfile
- entrypoint.sh
Self explanatory.
Bumps node to v18 lts and sets bash to -e for better error captures
> Update to node 18 and set bash -e for error catching

- entrypoint.sh
Testing ran here nothing else relevant was found 
https://github.com/sbe-arg/dummy-releases/actions 
@sammcj it's not urgent
> When running 1.63 in a fresh repo without tags it fails to validate existing tags

- entrypoint.sh
since we use || true there is no need for -s and -q results in an always null pretag var
this breaks some flows where we bump an existing pretag
> remove -qs from pre release tag case

- entrypoint.sh
RE: https://github.com/anothrNick/github-tag-action/issues/269
Fixes a pipefail error caused by piping output to the head function. Instead of using pipes, output is now saved into vars which are passed between functions.
NO
Tested by creating a repo with 998 tags and then running the workflow against it.
- Successful test run: https://github.com/baumac/actions-test-repo/actions/runs/5032916945/jobs/9026818958
-N/A
> Fix pipefail error caused by piping output to head

- .github/workflows/main.yml
- entrypoint.sh
Add permissions to actions token, errors here https://github.com/anothrNick/github-tag-action/actions/runs/5039598293/jobs/9037848230#step:4:265
Added a comment in entrypoint so merging this releases 1.66 as failed with permissions on https://github.com/anothrNick/github-tag-action/pull/270 (also we should consider adding releasing tags manually via workflow run)
> Suddenly existing repos fail with missing permissions for token

- entrypoint.sh
Changed the sorting of tags for the branch context to be based on the latest committed tag rather than the latest 'v' tag. This is to solve an issue where we had older v tags before we migrated to no v. 
Without this change the last v tag is selected rather than the last tag which was causing an error. 
Prior sorting for branch context :
Proposed change in this PR:
Not a breaking change
- Tested in my repos and works as intended, the latest tag is at the top of the list rather than the latest "v" tag
- Why was there a sort on the 'v' rather than just latest tag as that was causing a failure on our repo that had older v tags before moving to no v
> Sorting tags based on commit date for branch

- .github/workflows/main.yml
- .github/workflows/test.yml
- README.md
- entrypoint.sh
Change git tag over http to git cli
Fixes: https://github.com/anothrNick/github-tag-action/actions/runs/3372412451/jobs/5595804270#step:4:89 
My availability to test this is low.
But is what we use to tag the major tag in here https://github.com/anothrNick/github-tag-action/blob/master/.github/workflows/main.yml#L36-L50
I don't see why not use the same approach everywhere instead of soft tags.
We might need to add more checks to this.
> FIX: use git tag / git push instead of http soft tags

- README.md
solves #226, we won't over engineer it
> readme addition to warn using initial vX with with_v flags

- README.md
- entrypoint.sh
Adding a FORCE option to skip the condition if the release commit is the same commit from the tag.
This will allow users to create  hotfix from a last release branch.
Added the FORCE option and add also the condition to skip the validation on commit.
(YES / **NO**)
-
-
> Creating FORCE option

- Dockerfile
Update the node version from 18 to 20
(**YES** / NO)
-
-
> Upgrade node to version 20

- .github/workflows/main.yml
Use `pull_request_target` event to run in base of pr (workflow yaml)
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
NO
-
-
> Use pull_request_target event to run in base of pr

- README.md
- entrypoint.sh
NO
Since I added a new argument (FORCE_WITHOUT_CHANGES_PRE), there shouldn't be any.
Alternatively, we can use FORCE_WITHOUT_CHANGES for prereleases as well, which would imply a breaking change.
I've tried the fork on a private repo. It works as expected. The changes are also minimal so they should be fine.
> Fixes #309

- README.md
- entrypoint.sh
This PR reverts #313, which was reverting #310. 
It fixed #309.
According to: https://github.com/anothrNick/github-tag-action/pull/310#issuecomment-2052088893
> Revert "Merge pull request #313 from anothrNick/revert-310-master"

- .github/workflows/main.yml
- entrypoint.sh
Poking around in this repository, I saw your comment in your main workflow file that auto-release creation was broken. Seeing as I have auto-releases working splendidly for my organization, I figured I'd pass along my config if you were interested in using it.
Feel free to change/tweak/adjust whatever you like here, or to reject it entirely.  Completely up to you.
NO
Ran the workflow on my own forked repo [with success](https://github.com/gabriel-stackhouse/github-tag-action/releases/tag/0.1.0):
N/A
> Fix Auto Releases

- entrypoint.sh
Add an options for overriding the commit message with  custom tag message.
NO
Running locally.
-
-
> Add tag message override

- Dockerfile
I use Git LFS to track large files that seldomly change.
Git LFS adds some hooks to call into the `git-lfs` command.
However, this command is not installed in the Docker image produced by the action, so the entire action fails.
Adding the following step before github-tag-action can be used to circumvent the missing dependency:
```yaml
- name: Delete .git/hooks/*
run: rm -rf .git/hooks/*
```
I believe not, since `git-lfs` is only invoked if its hooks are enabled.
Docker build:
```bash
$ docker build --progress plain --no-cache .
#0 building with "default" instance using docker driver
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 370B done
#1 DONE 0.0s
#2 [internal] load metadata for …
```
> Add git-lfs to installed packages in Dockerfile

- entrypoint.sh
Removed the `tagPrefix` from the new tag when creating a `.0` prerelease tag. The prefix already gets added to the `new` variable at lines 178 to 198.
This should fix a bug that was introduced in PR #326 
NO
-
-
> Bugfix for duplicate prefix on first prerelease tag
